application: test

media:
  thumb_sizes:
    75:
      w: 75
      h: 75
    500:
      w: 500
      h: 500
    800:
      w: 800
      h: 800

amazon:
  access_key_id: accesskeyid
  access_key_secret: accesskeysecret